---
title: "Metodo Pivoteo"
author: "Nestor Ivan Jacobo Barrera"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Eliminacion Gaussiana con pivoteo parcial 

el sistema  a resolver es: 
5x+2y-3z+4w=1
-x+y+z-3w=2
6x+6y+4z+w=0
x-y-z+w=2
```{r}
valores <- c(5,-1,6,1,2,1,6,-1,-3,1,4,-1,4,-3,4,1)
A <- matrix(valores, nrow = 4 )
(A)
valoresb <- c(1,2,0,2)
b <- matrix(valoresb, nrow = 4)
(b)
valoresc <- c(5,2,-3,4,-1,1,1,-3,6,6,4,0,1,-1,-1,1)
tA <- matrix(valoresc, nrow = 4)
(tA)
(A)
Ab <- cbind(A, b)
(Ab)
bA <- cbind(b, A)
(bA)
Abt <- rbind(A,t(b))
(Abt)
btA <- rbind(t(b), A)
(btA)
```

```{r}
r1 <- Ab [3,]
(r1)
r2 <- Ab [2,]
(r2)
r3 <- Ab [1,]
r4 <- Ab [4,]
nM = rbind(r1,r2,r3,r4)
(nM)
```

```{r}
r1 <- nM[1, ]
(r1)
r2 <- nM[2, ]
(r2)
r3 <- nM[3, ]
(r3)
r4 <- nM[4,]
(r4)
c1 <- nM[ ,1]
(c1)
c2 <- nM[ ,2]
(c2)
c3 <- nM[ ,3]
(c3)
c4 <- nM[ ,4]
a11 <- nM[1,1]
(a11)
a22 <- nM[2,2]
(a22)
a32 <- nM[3,2]
(a32)
a23 <- nM[2,3]
(a23)
a14 <- nM[1,4]
(a14)
a24 <- nM[2,4]
(a24)
```

```{r}
m1 <- -nM[2,1]/nM[1,1]; (m1)
m2 <- -nM[3,1]/nM[1,1]; (m2)
m3 <- -nM[4,1]/nM[1,1]; (m3)
A1 <- nM[1,]
(A1)
A2 <- m1*nM[1,]+nM[2,]
(A2)
A3 <- m2*nM[1,]+nM[3,]
(A3)
A4 <- m3*nM[1,]+nM[4,] 
NuevaA <- rbind(A1,A2, A3, A4)
(NuevaA)
```

```{r}
r1 <- A1
(r1)
r2 <- A3
(r2)
r3 <- A2
(r3)
r4 <- A4
(r4)
nm <- rbind(r1,r2,r3,r4)
(nm)
```

```{r}
m4 <- -nm[3,2]/nm[2,2]; (m4)
m5 <- -nm[4,2]/nm[2,2]; (m5)
R1 <- nm[1,]
R2 <- nm[2,]
R3 <- m4*nm[2,]+nm[3,]; (R3)
R4 <- m5*nm[2,]+nm[4,]; (R4)
Nueva <- rbind(R1,R2,R3,R4)
(Nueva)
```

```{r}
m6 <- -Nueva[4,3]/Nueva[3,3]; m6
R1 <- Nueva[1,]
R2 <- Nueva[2,]
R3 <- Nueva[3,]
R4 <- m6*Nueva[3,] + Nueva[4,]
Final <- rbind(R1,R2,R3,R4)
(Final)
```

```{r}
R1 <- Final[1,]
R2 <- Final[2,]
R3 <- Final[3,]
R4 <- Final[4,]


w <- R4[5] / R4[4]
(w)
z <- (R3[5] - R3[4]*w) / R3[3]
(z)
y <- (R2[5] - R2[3]*z - R2[4]*w) / R2[2]
(y)
x <- (R1[5] - R1[2]*y - R1[3]*z - R1[4]*w) / R1[1]
(x)
```