---
title: "Nivel de contaminacion en la delegacion Iztapalapa en el mes de julio"
author: "Nestor Ivan Jacobo Barrera"
date: "2025-09-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
rm(list = ls())

```

```{r}
Contaminacion_lvl <- c(  0.7, 0.4, 0.4,
 0.5, 0.3, 0.3, 0.7, 0.5, 0.2, 0.2, 0.5, 0.8, 0.3, 0.9, 0.5, 0.2, 0.4, 0.4, 0.7, 0.6, 0.8,
 0.3, 1, 0.7, 1.5, 0.1, 0.1, 0.9, 0.1, 0.3, 0.9, 0.3, 1.2, 1.2, 1.2, 0.6, 0.7, 0.4, 1.8, 0.2,
 0.6, 0.7, 1.7, 0.4, 0.9, 0.2, 0.8, 1, 0.7, 0.6, 0.7, 0.3, 0.5, 0.2, 1.2, 0.5, 0.8, 0.2, 0.4,
 0.3, 0.4, 0.5, 0.5, 1.4, 0.4)
```

```{r}
summary(Contaminacion_lvl)
```

```{r}
Contaminacion_ord <- sort(Contaminacion_lvl); (Contaminacion_lvl)
cte <- 9
```

```{r}
indices <- 1:10; (indices)
t <- cte*indices; (t)
```

```{r}
mis_deciles <- Contaminacion_ord[t]; (mis_deciles)
cuantiles <- quantile(Contaminacion_lvl); (cuantiles)
Q1 <- cuantiles[2]; (Q1)
Q2 <- cuantiles[3]; (Q2)
Q3 <- cuantiles[4]; (Q3)
```

```{r}
x_media <- mean(Contaminacion_lvl);(x_media)
mi_min <- min(Contaminacion_lvl); (mi_min)
mi_max <- max(Contaminacion_lvl); (mi_max)
varianza <- var(Contaminacion_lvl); (varianza) 
DesvEst <- sd(Contaminacion_lvl); (DesvEst)
```

```{r}
plot(
  Contaminacion_lvl,
  main = "Niveles de Contaminacion",
  xlab = "Nivel Contaminacion",
  ylab = "Numero (Contaminacion)",
  col = "blue",       
  pch = 19,           
  cex = 0.5,          
  cex.main = 1.5,     
  cex.lab = 1.2,      
  col.main = "darkred")
legend(
  "topright",                 
  legend = c(mi_min,mi_max),    
  pch = 17,
  col=c("purple","orange"),
  pt.cex = 1.5,                
  cex = 0.7,
  bty = "n"                    
)
abline(h = x_media, col = "red", lwd = 1, lty = 2)     
abline(h = Q2, col = "lightgreen", lwd = 1, lty = 3) 
abline(h = mis_deciles, col = "lightgray", lty = 1.5)
points(which.min(Contaminacion_lvl), min(Contaminacion_lvl), col = "purple", pch = 17, cex = 1.5)
points(which.max(Contaminacion_lvl), max(Contaminacion_lvl), col = "orange", pch = 17, cex = 1.5)
```

```{r}
nbreaks=10;
miscolores <- rainbow(25,0.85);
h <- hist(Contaminacion_lvl, breaks = nbreaks, col= miscolores, 
          main = 'Nivel de Contaminacion',
          xlab="Contaminacion",
          ylab="Frecuencias")
text(h$mids, h$counts, labels = h$counts, pos = 3, cex = 0.4, 
     col = "black")
nl <- length(h$counts); 
legend(
  "topright",                  # ubicación
  legend = h$counts,    # etiquetas
  fill = miscolores,
  col = miscolores,    # colores (uno por cada símbolo)
  pt.cex = 1.5,                # tamaño de los símbolos
  cex = 0.7,
  bty = "n"                    # sin borde en la caja
)
```

```{r}
nbreaks=10;
h2 <- hist(Contaminacion_lvl, breaks = nbreaks, col= miscolores, 
           main = 'Nivel de Contaminacion',
           xlab="Contaminacion",
           ylab="Frecuencias",
           ylim=c(0,max(h$counts)*1.5))
text(h$mids, h$counts, labels = h$counts, pos = 3, cex = 0.8, 
     col = "black")
nl <- length(h$counts); 
legend(
  "topright",                
  legend = h$counts,    
  fill = miscolores,
  col = miscolores,    
  pt.cex = 1.5,               
  cex = 0.5,
  bty = "n"                    
)
```

```{r}
h3 <- hist(Contaminacion_lvl, 
           breaks = nbreaks, 
           col= miscolores, 
           main = 'Nivel de contaminacion',
           xlab="Contaminacion",
           ylab="Porcentaje",
           ylim=c(0,max(h$density)*1.5),
           probability=TRUE)
porcentajes <- h3$counts/sum(h3$counts)*100

text(h3$mids, 
     h3$density, 
     labels = paste0(round(porcentajes,1),"%"),
     pos = 3, 
     cex = 0.8, 
     col = "black")

nl <- length(h3$counts); (nl)
legend(
  "topright",                
  legend = paste0(round(porcentajes,1),"%"),
  fill = miscolores,
  cex = 0.5,
  bty = "n"                   
)
```

```{r}
nbreaks <- 10
intervalos <- cut(Contaminacion_lvl, breaks = nbreaks); (intervalos)
tabla <- table(intervalos); (tabla)
porcentajes <- round(prop.table(tabla) * 100, 1); (porcentajes)
pie(tabla,
    main = "Contaminacion ",
    col = rainbow(length(tabla)),
    labels = paste0(porcentajes, "%"))
```

```{r}
##---- Grafica combinada ----
nbreaks <- 10
h <- hist(Contaminacion_lvl, breaks = nbreaks, plot = FALSE)
hist(Contaminacion_lvl,
     breaks = nbreaks,
     col = "lightblue",
     main = "Histograma y Ojiva (%)",
     xlab = "Contaminacion",
     ylab = "Frecuencia")
freq_acum_pct <- cumsum(h$counts) / sum(h$counts) * 100
x_vals <- h$breaks[-1]
par(new = TRUE)
plot(x_vals, freq_acum_pct,
     type = "o", pch = 19, lwd = 2, col = "red",
     axes = FALSE, xlab = "", ylab = "",
     xlim = range(h$breaks), ylim = c(0, 100))
axis(4)                           
```