---
title: "Peso corporal en kilogramos"
author: "Nestor Ivan Jacobo Barrera"
date: "2025-09-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
rm(list = ls())

```

```{r}
Peso_kilos <- c( 100.5, 91.3, 60.4, 83.2, 49.6, 103.1, 60.3, 109.3, 83.5,
 63.9, 106, 50, 47, 89.7, 108.5, 78.9, 82.7, 60.7, 98.7, 85.2, 48.7, 106.7, 63.9, 84.1,
 69.5, 53.3, 108.9, 91.8, 108.6, 54.5, 95.1, 90.6, 115.9, 88.5, 67.7, 115.1, 108.3, 76.8,
 81.4, 102.6, 63.9, 105.9, 106.7, 76.3, 113.7, 50.3, 105.8, 81.4, 67.9, 91.3, 68.9, 93.9,
 113.7, 87.7, 92.8, 76.2, 104.7, 109.7, 72.6, 81.6, 112.2, 79.8, 60.7, 95.7, 100.1, 94,
 60.5, 117.1, 45.5, 112.7, 51.7, 107.8, 86.6, 90.3, 105.9, 64.7, 48, 55.4, 52.9, 58.2,
 117.1, 59.6, 69.9, 96.9, 97, 66.5, 67.4, 77.2, 73.7, 113)
```

```{r}
summary(Peso_kilos)
```

```{r}
Peso_ord <- sort(Peso_kilos); (Peso_ord)
cte <- 9
```

```{r}
indices <- 1:10; (indices)
t <- cte*indices; (t)
```

```{r}
mis_deciles <- Peso_ord[t]; (mis_deciles)
cuantiles <- quantile(Peso_kilos); (cuantiles)
Q1 <- cuantiles[2]; (Q1)
Q2 <- cuantiles[3]; (Q2)
Q3 <- cuantiles[4]; (Q3)
```

```{r}
x_media <- mean(Peso_kilos);(x_media)
mi_min <- min(Peso_kilos); (mi_min)
mi_max <- max(Peso_kilos); (mi_max)
varianza <- var(Peso_kilos); (varianza) 
DesvEst <- sd(Peso_kilos); (DesvEst)
```

```{r}
plot(
  Peso_kilos,
  main = "Gráfica Peso Corporal en Kilogramos",
  xlab = "Índice de Peso",
  ylab = "Numero (Kilos)",
  col = "blue",       
  pch = 19,           
  cex = 0.5,          
  cex.main = 1.5,     
  cex.lab = 1.2,      
  col.main = "darkred")
legend(
  "topright",                 
  legend = c(mi_min,mi_max),    
  pch = 17,
  col=c("purple","orange"),
  pt.cex = 1.5,                
  cex = 0.7,
  bty = "n"                    
)
abline(h = x_media, col = "red", lwd = 1, lty = 2)     
abline(h = Q2, col = "lightgreen", lwd = 1, lty = 3) 
abline(h = mis_deciles, col = "lightgray", lty = 1.5)
points(which.min(Peso_kilos), min(Peso_kilos), col = "purple", pch = 17, cex = 1.5)
points(which.max(Peso_kilos), max(Peso_kilos), col = "orange", pch = 17, cex = 1.5)
```

```{r}
nbreaks=10;
miscolores <- rainbow(25,0.85);
h <- hist(Peso_kilos, breaks = nbreaks, col= miscolores, 
          main = ' Peso en Kilogramos',
          xlab="Peso",
          ylab="Frecuencias")
text(h$mids, h$counts, labels = h$counts, pos = 3, cex = 0.4, 
     col = "black")
nl <- length(h$counts); 
legend(
  "topright",                  # ubicación
  legend = h$counts,    # etiquetas
  fill = miscolores,
  col = miscolores,    # colores (uno por cada símbolo)
  pt.cex = 1.5,                # tamaño de los símbolos
  cex = 0.7,
  bty = "n"                    # sin borde en la caja
)
```

```{r}
nbreaks=10;
h2 <- hist(Peso_kilos, breaks = nbreaks, col= miscolores, 
           main = 'Numero de Peso en Kg',
           xlab="Peso",
           ylab="Frecuencias",
           ylim=c(0,max(h$counts)*1.5))
text(h$mids, h$counts, labels = h$counts, pos = 3, cex = 0.8, 
     col = "black")
nl <- length(h$counts); 
legend(
  "topright",                
  legend = h$counts,    
  fill = miscolores,
  col = miscolores,    
  pt.cex = 1.5,               
  cex = 0.5,
  bty = "n"                    
)
```

```{r}
h3 <- hist(Peso_kilos, 
           breaks = nbreaks, 
           col= miscolores, 
           main = 'Peso en Kilogramos',
           xlab="Peso",
           ylab="Porcentaje",
           ylim=c(0,max(h$density)*1.5),
           probability=TRUE)
porcentajes <- h3$counts/sum(h3$counts)*100

text(h3$mids, 
     h3$density, 
     labels = paste0(round(porcentajes,1),"%"),
     pos = 3, 
     cex = 0.8, 
     col = "black")

nl <- length(h3$counts); (nl)
legend(
  "topright",                
  legend = paste0(round(porcentajes,1),"%"),
  fill = miscolores,
  cex = 0.5,
  bty = "n"                   
)
```

```{r}
nbreaks <- 10
intervalos <- cut(Peso_kilos, breaks = nbreaks); (intervalos)
tabla <- table(intervalos); (tabla)
porcentajes <- round(prop.table(tabla) * 100, 1); (porcentajes)
pie(tabla,
    main = "Peso en kilos ",
    col = rainbow(length(tabla)),
    labels = paste0(porcentajes, "%"))
```

```{r}
##---- Grafica combinada ----
nbreaks <- 10
h <- hist(Peso_kilos, breaks = nbreaks, plot = FALSE)
hist(Peso_kilos,
     breaks = nbreaks,
     col = "lightblue",
     main = "Histograma y Ojiva (%)",
     xlab = "Peso",
     ylab = "Frecuencia")
freq_acum_pct <- cumsum(h$counts) / sum(h$counts) * 100
x_vals <- h$breaks[-1]
par(new = TRUE)
plot(x_vals, freq_acum_pct,
     type = "o", pch = 19, lwd = 2, col = "red",
     axes = FALSE, xlab = "", ylab = "",
     xlim = range(h$breaks), ylim = c(0, 100))
axis(4)                           
```