---
title: "Numero de estudiantes en un salon"
author: "Nestor Ivan Jacobo Barrera"
date: "2025-09-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
rm(list = ls())

```

```{r}
Numero_estudiantes <- c( 35, 37, 13, 6, 40, 42, 11, 24, 24, 33, 8, 34, 21,
 23, 34, 24, 45, 39, 38, 35, 9, 39, 38, 45, 7, 35, 22, 28, 38, 6, 5, 45, 36, 18, 37, 45,
 13, 31, 23, 43.)
```

```{r}
summary(Numero_estudiantes)
```

```{r}
Estudiantes_ord <- sort(Numero_estudiantes); (Estudiantes_ord)
cte <- 9
```

```{r}
indices <- 1:10; (indices)
t <- cte*indices; (t)
```

```{r}
mis_deciles <- Estudiantes_ord[t]; (mis_deciles)
cuantiles <- quantile(Numero_estudiantes); (cuantiles)
Q1 <- cuantiles[2]; (Q1)
Q2 <- cuantiles[3]; (Q2)
Q3 <- cuantiles[4]; (Q3)
```

```{r}
x_media <- mean(Numero_estudiantes);(x_media)
mi_min <- min(Numero_estudiantes); (mi_min)
mi_max <- max(Numero_estudiantes); (mi_max)
varianza <- var(Numero_estudiantes); (varianza) 
DesvEst <- sd(Numero_estudiantes); (DesvEst)
```

```{r}
plot(
  Numero_estudiantes,
  main = "Numero de Estudiantes en un Salon",
  xlab = "Estudiantes",
  ylab = "Numero (Estudiantes)",
  col = "blue",       
  pch = 19,           
  cex = 0.5,          
  cex.main = 1.5,     
  cex.lab = 1.2,      
  col.main = "darkred")
legend(
  "topright",                  # ubicación
  legend = c(mi_min,mi_max),    # etiquetas
  pch = 17,
  col=c("purple","orange"),
  pt.cex = 1.5,                # tamaño de los símbolos
  cex = 0.7,
  bty = "n"                    # sin borde en la caja
)
abline(h = x_media, col = "red", lwd = 1, lty = 2)     
abline(h = Q2, col = "lightgreen", lwd = 1, lty = 3) 
abline(h = mis_deciles, col = "lightgray", lty = 1.5)
points(which.min(Numero_estudiantes), min(Numero_estudiantes), col = "purple", pch = 17, cex = 1.5)
points(which.max(Numero_estudiantes), max(Numero_estudiantes), col = "orange", pch = 17, cex = 1.5)
```

```{r}
nbreaks=10;
miscolores <- rainbow(25,0.85);
h <- hist(Numero_estudiantes, breaks = nbreaks, col= miscolores, 
          main = 'Numero de Estudiantes',
          xlab="Estudiantes",
          ylab="Numero (estudiantes)")

text(h$mids, h$counts, labels = h$counts, pos = 3, cex = 0.4, 
     col = "black")
nl <- length(h$counts); 
legend(
  "topright",                  # ubicación
  legend = h$counts,    # etiquetas
  fill = miscolores,
  col = miscolores,    # colores (uno por cada símbolo)
  pt.cex = 1.5,                # tamaño de los símbolos
  cex = 0.7,
  bty = "n"                    # sin borde en la caja
)
```

```{r}
##---- Mejora del grafico ----
h2 <- hist(Numero_estudiantes, breaks = nbreaks, col= miscolores, 
           main = 'Numero de Estudiantes',
           xlab="Estudiantes",
           ylab="Numero(estudiantes)",
           ylim=c(0,max(h$counts)*1.5))
text(h$mids, h$counts, labels = h$counts, pos = 3, cex = 0.8, 
     col = "black")
nl <- length(h$counts); 
legend(
  "topright",                  # ubicación
  legend = h$counts,    # etiquetas
  fill = miscolores,
  col = miscolores,    # colores (uno por cada símbolo)
  pt.cex = 1.5,                # tamaño de los símbolos
  cex = 0.5,
  bty = "n"                    # sin borde en la caja
)
```

```{r}
##---- Grafico con porcentajes ----
h3 <- hist(Numero_estudiantes, 
           breaks = nbreaks, 
           col= miscolores, 
           main = 'Numero de Estudiantes',
           xlab="Numero Estudiantes",
           ylab="Porcentaje",
           ylim=c(0,max(h$density)*1.5),
           probability=TRUE)
porcentajes <- h3$counts/sum(h3$counts)*100

text(h3$mids, 
     h3$density, 
     labels = paste0(round(porcentajes,1),"%"),
     pos = 3, 
     cex = 0.8, 
     col = "black")

nl <- length(h3$counts); (nl)
legend(
  "topright",                  # ubicación
  legend = paste0(round(porcentajes,1),"%"),
  fill = miscolores,
  cex = 0.5,
  bty = "n"                    # sin borde en la caja
)
```

```{r}
#---- Graficos de pastel ----
# Tus datos
nbreaks <- 10
intervalos <- cut(Numero_estudiantes, breaks = nbreaks); (intervalos)
tabla <- table(intervalos); (tabla)
porcentajes <- round(prop.table(tabla) * 100, 1); (porcentajes)
pie(tabla,
    main = "Numero de Estudiantes",
    col = rainbow(length(tabla)),
    labels = paste0(porcentajes, "%"))
```

```{r}
##---- Grafica combinada ----
nbreaks <- 10
h <- hist(Numero_estudiantes, breaks = nbreaks, plot = FALSE)
hist(Numero_estudiantes,
     breaks = nbreaks,
     col = "lightblue",
     main = "Histograma y Ojiva (%)",
     xlab = "Numero (Estudiantes)",
     ylab = "Frecuencia")
freq_acum_pct <- cumsum(h$counts) / sum(h$counts) * 100
x_vals <- h$breaks[-1]
par(new = TRUE)
plot(x_vals, freq_acum_pct,
     type = "o", pch = 19, lwd = 2, col = "red",
     axes = FALSE, xlab = "", ylab = "",
     xlim = range(h$breaks), ylim = c(0, 100))
axis(4)                           
```